---
# tasks file for ansible-mongo-standalone
 - name: Ensure MongoDB yum repository exists (RedHat)
   yum_repository:
       name: "mongodb-org-{{ mongodb_version }}"
           description: "Official MongoDB {{ mongodb_version }} yum repo"
               baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_version }}/x86_64/"
                   gpgcheck: 1
                       gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
                         when: ansible_os_family == "RedHat"

 - name: Install MongoDB Packages
   package:
       name: "{{ mongodb_packages }}"
           state: present
